/*
   -- eXplorer --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__HARDSERIAL


// RemoteXY connection settings 
#define REMOTEXY_SERIAL Serial
#define REMOTEXY_SERIAL_SPEED 9600


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 162 bytes V19 
  { 255,7,0,0,0,155,0,19,0,0,0,101,88,112,108,111,114,101,114,0,
  24,1,200,84,1,1,10,0,1,5,42,64,36,1,2,31,82,69,86,0,
  1,5,4,64,36,1,2,31,70,87,68,0,4,80,26,12,36,0,34,26,
  1,170,5,26,74,1,2,31,82,0,1,140,5,27,74,1,2,31,76,0,
  10,115,32,16,16,48,4,26,31,79,78,0,31,79,70,70,0,10,115,57,
  17,17,48,4,26,31,79,78,0,31,79,70,70,0,129,79,63,14,5,64,
  17,115,112,101,101,100,0,129,115,27,16,4,64,17,112,111,115,32,108,105,
  103,104,116,0,129,114,52,19,4,64,17,104,101,97,100,108,105,103,104,116,
  115,0 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  uint8_t button_02; // =1 if button pressed, else =0, from 0 to 1
  uint8_t button_01; // =1 if button pressed, else =0, from 0 to 1
  int8_t slider_01; // from 0 to 100
  uint8_t button_03; // =1 if button pressed, else =0, from 0 to 1
  uint8_t button_04; // =1 if button pressed, else =0, from 0 to 1
  uint8_t pushSwitch_01; // =1 if state is ON, else =0, from 0 to 1
  uint8_t pushSwitch_02; // =1 if state is ON, else =0, from 0 to 1

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////




void setup() 
{
  RemoteXY_Init ();  // initialization by macros 
  
  
  // TODO you setup code
  
}

void loop() 
{ 
  RemoteXYEngine.handler ();   
   
  
  // TODO you loop code
  // use the RemoteXY structure for data transfer
  // do not call delay(), use instead RemoteXYEngine.delay() 

}